### ISSUE TITLE
Cannot compile on VS 2017

### ISSUE THREAD

**Issue by magicseb** [jakcron/NXTools#1]
This cannot be compiled on VS 2017 since this [commit](https://github.com/jakcron/NXTools/commit/4cfcf6bae975dba823d2f2a8ea1a7b173a638054)

Got an error C2971 during compiling

`Erreur	C2971	'ISerialiseablePrimative' : paramètre de modèle 'F' : 'le_hword' : une variable avec une durée de stockage non statique ne peut pas être utilisée comme argument sans type	libfnd	d:\switch\nxtools-4cfcf6bae975dba823d2f2a8ea1a7b173a638054\lib\libfnd\include\fnd\endian.h	51`

**Comment by jakcron** [comment]
I wasn't aware that it even compiled on VS 2017.

I just use VS for the code editor. But I'll look into fixing this compiler error.

**Comment by jakcron** [comment]
Fixed in https://github.com/jakcron/NXTools/commit/27347214f7bfd7de0f984837ad5d646d318addaa
